CREATE DATABASE HugoLR2

CREATE TABLE Collection (
  Id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  Name VARCHAR(200) NOT NULL
);

CREATE TABLE Artist (
  Id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(200) NOT NULL
);

CREATE TABLE Album (
  Id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  Name VARCHAR(200) NOT NULL,
  CollectionId INT,
  ArtistId INT,
  FOREIGN KEY (CollectionId) REFERENCES Collection(Id),
  FOREIGN KEY	(ArtistId) REFERENCES Artist(Id)
);

CREATE TABLE Track (
  Id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  Name VARCHAR(200) NOT NULL,
  Trackduration Int,
  AlbumId Int,
  FOREIGN KEY (AlbumId) REFERENCES Album(Id)g
);
